import { DollarSign, Users, CreditCard, Activity, ShoppingCart, Percent, Target, RefreshCw, Zap } from "lucide-react"
import type { ActivityData, APIKeyData, APIUsageData, AssetData, CustomerData, KPIData, NotificationSetting, OverviewData, ProductData, ProfileData, RegionData, RevenueData, SecuritySetting, StockData, Transaction, UserData } from "@/types"

// KPI data
export const kpiData: KPIData[] = [
  {
    title: "Total Revenue",
    value: "$1,245,890",
    change: "+18.7%",
    trend: "up",
    icon: DollarSign,
  },
  {
    title: "Active Users",
    value: "12,345",
    change: "+15.3%",
    trend: "up",
    icon: Users,
  },
  {
    title: "Transactions",
    value: "48,592",
    change: "+24.5%",
    trend: "up",
    icon: CreditCard,
  },
  {
    title: "Avg. Order Value",
    value: "$258",
    change: "+12.2%",
    trend: "up",
    icon: ShoppingCart,
  },
  {
    title: "Conversion Rate",
    value: "3.8%",
    change: "+0.5%",
    trend: "up",
    icon: Percent,
  },
  {
    title: "Customer Acquisition",
    value: "$42",
    change: "-8.1%",
    trend: "down",
    icon: Target,
  },
  {
    title: "Active Subscriptions",
    value: "8,942",
    change: "+5.3%",
    trend: "up",
    icon: RefreshCw,
  },
  {
    title: "Churn Rate",
    value: "2.1%",
    change: "-0.3%",
    trend: "up",
    icon: Zap,
  },
]

// Dashboard stats cards data
export const statsCardsData = [
  {
    title: "Total Revenue",
    value: "$45,231.89",
    change: "+20.1% from last month",
    trend: "up",
    icon: DollarSign,
  },
  {
    title: "New Customers",
    value: "2,350",
    change: "+180.1% from last month",
    trend: "up",
    icon: Users,
  },
  {
    title: "Active Subscriptions",
    value: "1,200",
    change: "+19% from last month",
    trend: "up",
    icon: CreditCard,
  },
  {
    title: "Active Users",
    value: "573",
    change: "-2% from last month",
    trend: "down",
    icon: Activity,
  },
]

// Revenue Forecast Data
export const revenueData: RevenueData[] = [
  { month: "Jan", actual: 125000, forecast: 120000 },
  { month: "Feb", actual: 132000, forecast: 130000 },
  { month: "Mar", actual: 141000, forecast: 138000 },
  { month: "Apr", actual: 160000, forecast: 150000 },
  { month: "May", actual: 175000, forecast: 170000 },
  { month: "Jun", actual: 168000, forecast: 180000 },
  { month: "Jul", actual: 192000, forecast: 190000 },
  { month: "Aug", actual: 205000, forecast: 200000 },
  { month: "Sep", actual: 198000, forecast: 210000 },
  { month: "Oct", actual: 215000, forecast: 220000 },
  { month: "Nov", actual: 230000, forecast: 230000 },
  { month: "Dec", actual: 245000, forecast: 240000 },
]

// Customer Growth Data
export const customerData: CustomerData[] = [
  { month: "Jan", new: 1200, returning: 3500, churn: 250 },
  { month: "Feb", new: 1350, returning: 3600, churn: 280 },
  { month: "Mar", new: 1400, returning: 3750, churn: 300 },
  { month: "Apr", new: 1500, returning: 3900, churn: 270 },
  { month: "May", new: 1650, returning: 4050, churn: 290 },
  { month: "Jun", new: 1800, returning: 4200, churn: 310 },
  { month: "Jul", new: 1950, returning: 4350, churn: 330 },
  { month: "Aug", new: 2100, returning: 4500, churn: 350 },
  { month: "Sep", new: 2250, returning: 4650, churn: 370 },
  { month: "Oct", new: 2400, returning: 4800, churn: 390 },
  { month: "Nov", new: 2550, returning: 4950, churn: 410 },
  { month: "Dec", new: 2700, returning: 5100, churn: 430 },
]

// Region Data
export const regionData: RegionData[] = [
  { name: "North America", value: 42, users: 7850 },
  { name: "Europe", value: 28, users: 5230 },
  { name: "Asia Pacific", value: 18, users: 3360 },
  { name: "Latin America", value: 8, users: 1490 },
  { name: "Middle East & Africa", value: 4, users: 750 },
]

// Product Data
export const productData: ProductData[] = [
  { name: "Premium Trading", sales: 12500, revenue: 625000, growth: 15.2 },
  { name: "Wealth Management", sales: 8750, revenue: 437500, growth: 12.8 },
  { name: "Retirement Planning", sales: 6300, revenue: 315000, growth: 8.5 },
  { name: "Tax Optimization", sales: 4200, revenue: 210000, growth: 5.3 },
  { name: "Insurance Products", sales: 3100, revenue: 155000, growth: -2.7 },
  { name: "Crypto Trading", sales: 2800, revenue: 140000, growth: 22.4 },
  { name: "Robo-Advisory", sales: 2500, revenue: 125000, growth: 18.9 },
]

// Transaction Data
export const transactionData: Transaction[] = [
  {
    id: "TX-78945",
    amount: "$2,500.00",
    name: "John Doe",
    email: "john.doe@example.com",
    status: "completed",
    date: "2023-06-01",
    type: "deposit",
    category: "Investment",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TX-78946",
    amount: "$1,200.00",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    status: "pending",
    date: "2023-06-02",
    type: "withdrawal",
    category: "Savings",
    paymentMethod: "ACH",
  },
  {
    id: "TX-78947",
    amount: "$3,750.00",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    status: "completed",
    date: "2023-06-03",
    type: "deposit",
    category: "Retirement",
    paymentMethod: "Wire Transfer",
  },
  {
    id: "TX-78948",
    amount: "$850.00",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    status: "failed",
    date: "2023-06-03",
    type: "withdrawal",
    category: "Personal",
    paymentMethod: "Credit Card",
  },
  {
    id: "TX-78949",
    amount: "$5,000.00",
    name: "Michael Wilson",
    email: "michael.wilson@example.com",
    status: "completed",
    date: "2023-06-04",
    type: "deposit",
    category: "Investment",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TX-78950",
    amount: "$1,500.00",
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    status: "completed",
    date: "2023-06-05",
    type: "withdrawal",
    category: "Education",
    paymentMethod: "ACH",
  },
  {
    id: "TX-78951",
    amount: "$2,200.00",
    name: "David Miller",
    email: "david.miller@example.com",
    status: "pending",
    date: "2023-06-05",
    type: "deposit",
    category: "Investment",
    paymentMethod: "Wire Transfer",
  },
  {
    id: "TX-78952",
    amount: "$750.00",
    name: "Jennifer Taylor",
    email: "jennifer.taylor@example.com",
    status: "completed",
    date: "2023-06-06",
    type: "withdrawal",
    category: "Personal",
    paymentMethod: "Credit Card",
  },
  {
    id: "TX-78953",
    amount: "$3,200.00",
    name: "Christopher Anderson",
    email: "christopher.anderson@example.com",
    status: "completed",
    date: "2023-06-07",
    type: "deposit",
    category: "Retirement",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TX-78954",
    amount: "$1,800.00",
    name: "Jessica Thomas",
    email: "jessica.thomas@example.com",
    status: "failed",
    date: "2023-06-08",
    type: "withdrawal",
    category: "Investment",
    paymentMethod: "ACH",
  },
  {
    id: "TX-78955",
    amount: "$4,500.00",
    name: "Daniel Jackson",
    email: "daniel.jackson@example.com",
    status: "completed",
    date: "2023-06-09",
    type: "deposit",
    category: "Savings",
    paymentMethod: "Wire Transfer",
  },
  {
    id: "TX-78956",
    amount: "$950.00",
    name: "Amanda White",
    email: "amanda.white@example.com",
    status: "pending",
    date: "2023-06-10",
    type: "withdrawal",
    category: "Personal",
    paymentMethod: "Credit Card",
  },
  {
    id: "TX-78957",
    amount: "$2,800.00",
    name: "Matthew Harris",
    email: "matthew.harris@example.com",
    status: "completed",
    date: "2023-06-11",
    type: "deposit",
    category: "Investment",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TX-78958",
    amount: "$1,350.00",
    name: "Olivia Martin",
    email: "olivia.martin@example.com",
    status: "completed",
    date: "2023-06-12",
    type: "withdrawal",
    category: "Education",
    paymentMethod: "ACH",
  },
  {
    id: "TX-78959",
    amount: "$6,000.00",
    name: "Andrew Thompson",
    email: "andrew.thompson@example.com",
    status: "pending",
    date: "2023-06-13",
    type: "deposit",
    category: "Retirement",
    paymentMethod: "Wire Transfer",
  },
  {
    id: "TX-78960",
    amount: "$1,100.00",
    name: "Sophia Garcia",
    email: "sophia.garcia@example.com",
    status: "failed",
    date: "2023-06-14",
    type: "withdrawal",
    category: "Personal",
    paymentMethod: "Credit Card",
  },
  {
    id: "TX-78961",
    amount: "$3,900.00",
    name: "Joshua Martinez",
    email: "joshua.martinez@example.com",
    status: "completed",
    date: "2023-06-15",
    type: "deposit",
    category: "Investment",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TX-78962",
    amount: "$2,100.00",
    name: "Elizabeth Robinson",
    email: "elizabeth.robinson@example.com",
    status: "completed",
    date: "2023-06-16",
    type: "withdrawal",
    category: "Savings",
    paymentMethod: "ACH",
  },
  {
    id: "TX-78963",
    amount: "$4,200.00",
    name: "Ryan Clark",
    email: "ryan.clark@example.com",
    status: "pending",
    date: "2023-06-17",
    type: "deposit",
    category: "Retirement",
    paymentMethod: "Wire Transfer",
  },
  {
    id: "TX-78964",
    amount: "$800.00",
    name: "Megan Rodriguez",
    email: "megan.rodriguez@example.com",
    status: "completed",
    date: "2023-06-18",
    type: "withdrawal",
    category: "Personal",
    paymentMethod: "Credit Card",
  },
]

// User Data
export const userData: UserData[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    role: "admin",
    status: "active",
    lastLogin: "2023-06-18 14:32:45",
    createdAt: "2022-01-15",
    location: "New York, USA",
    department: "Executive",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "user",
    status: "active",
    lastLogin: "2023-06-17 09:15:22",
    createdAt: "2022-02-20",
    location: "London, UK",
    department: "Finance",
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    role: "manager",
    status: "active",
    lastLogin: "2023-06-18 11:45:30",
    createdAt: "2022-03-10",
    location: "Chicago, USA",
    department: "Operations",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    role: "user",
    status: "inactive",
    lastLogin: "2023-05-25 16:20:10",
    createdAt: "2022-04-05",
    location: "Toronto, Canada",
    department: "Marketing",
  },
  {
    id: 5,
    name: "Michael Wilson",
    email: "michael.wilson@example.com",
    role: "user",
    status: "active",
    lastLogin: "2023-06-18 08:55:15",
    createdAt: "2022-05-12",
    location: "Sydney, Australia",
    department: "Sales",
  },
  {
    id: 6,
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    role: "manager",
    status: "active",
    lastLogin: "2023-06-17 14:10:45",
    createdAt: "2022-06-18",
    location: "Berlin, Germany",
    department: "Customer Support",
  },
  {
    id: 7,
    name: "David Miller",
    email: "david.miller@example.com",
    role: "user",
    status: "pending",
    lastLogin: "2023-06-15 10:30:20",
    createdAt: "2022-07-22",
    location: "Paris, France",
    department: "IT",
  },
  {
    id: 8,
    name: "Jennifer Taylor",
    email: "jennifer.taylor@example.com",
    role: "user",
    status: "active",
    lastLogin: "2023-06-18 13:25:40",
    createdAt: "2022-08-30",
    location: "Tokyo, Japan",
    department: "HR",
  },
  {
    id: 9,
    name: "Christopher Anderson",
    email: "christopher.anderson@example.com",
    role: "admin",
    status: "active",
    lastLogin: "2023-06-18 09:45:15",
    createdAt: "2022-09-14",
    location: "San Francisco, USA",
    department: "Executive",
  },
  {
    id: 10,
    name: "Jessica Thomas",
    email: "jessica.thomas@example.com",
    role: "user",
    status: "inactive",
    lastLogin: "2023-05-30 11:20:35",
    createdAt: "2022-10-05",
    location: "Singapore",
    department: "Finance",
  },
  {
    id: 11,
    name: "Daniel Jackson",
    email: "daniel.jackson@example.com",
    role: "manager",
    status: "active",
    lastLogin: "2023-06-17 15:40:25",
    createdAt: "2022-11-18",
    location: "Amsterdam, Netherlands",
    department: "Operations",
  },
  {
    id: 12,
    name: "Amanda White",
    email: "amanda.white@example.com",
    role: "user",
    status: "pending",
    lastLogin: "2023-06-14 12:15:50",
    createdAt: "2022-12-22",
    location: "Madrid, Spain",
    department: "Marketing",
  },
  {
    id: 13,
    name: "Matthew Harris",
    email: "matthew.harris@example.com",
    role: "user",
    status: "active",
    lastLogin: "2023-06-18 10:10:30",
    createdAt: "2023-01-08",
    location: "Rome, Italy",
    department: "Sales",
  },
  {
    id: 14,
    name: "Olivia Martin",
    email: "olivia.martin@example.com",
    role: "manager",
    status: "active",
    lastLogin: "2023-06-17 16:55:20",
    createdAt: "2023-02-15",
    location: "Stockholm, Sweden",
    department: "Customer Support",
  },
  {
    id: 15,
    name: "Andrew Thompson",
    email: "andrew.thompson@example.com",
    role: "user",
    status: "active",
    lastLogin: "2023-06-18 08:30:45",
    createdAt: "2023-03-20",
    location: "Dublin, Ireland",
    department: "IT",
  },
]

// Stock Data
export const stockData: StockData[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 182.63,
    change: 2.35,
    changePercent: 1.3,
    volume: 58432156,
    marketCap: "2.87T",
    sector: "Technology",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 337.22,
    change: 3.78,
    changePercent: 1.13,
    volume: 23145678,
    marketCap: "2.51T",
    sector: "Technology",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 125.3,
    change: -0.85,
    changePercent: -0.67,
    volume: 19876543,
    marketCap: "1.58T",
    sector: "Technology",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    price: 129.18,
    change: 1.42,
    changePercent: 1.11,
    volume: 32145678,
    marketCap: "1.33T",
    sector: "Consumer Cyclical",
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 248.5,
    change: 5.32,
    changePercent: 2.19,
    volume: 45678912,
    marketCap: "788.5B",
    sector: "Automotive",
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    price: 287.05,
    change: -1.23,
    changePercent: -0.43,
    volume: 18765432,
    marketCap: "736.2B",
    sector: "Technology",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 419.38,
    change: 8.75,
    changePercent: 2.13,
    volume: 39876543,
    marketCap: "1.03T",
    sector: "Technology",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 143.45,
    change: -0.32,
    changePercent: -0.22,
    volume: 12345678,
    marketCap: "418.7B",
    sector: "Financial Services",
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    price: 235.78,
    change: 1.85,
    changePercent: 0.79,
    volume: 8765432,
    marketCap: "489.3B",
    sector: "Financial Services",
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    price: 154.32,
    change: 0.56,
    changePercent: 0.36,
    volume: 7654321,
    marketCap: "415.6B",
    sector: "Consumer Defensive",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    price: 162.15,
    change: -1.05,
    changePercent: -0.64,
    volume: 6543210,
    marketCap: "421.2B",
    sector: "Healthcare",
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    price: 145.68,
    change: 0.78,
    changePercent: 0.54,
    volume: 5432109,
    marketCap: "343.5B",
    sector: "Consumer Defensive",
  },
]

// Asset Allocation Data
export const assetData: AssetData[] = [
  { name: "Stocks", value: 45, change: 2.3, color: "#0088FE" },
  { name: "Bonds", value: 25, change: -0.5, color: "#00C49F" },
  { name: "Real Estate", value: 15, change: 1.2, color: "#FFBB28" },
  { name: "Cryptocurrencies", value: 10, change: 5.7, color: "#FF8042" },
  { name: "Commodities", value: 5, change: 0.8, color: "#8884d8" },
]

// API Key Data
export const apiKeyData: APIKeyData[] = [
  {
    id: "key_1a2b3c4d",
    name: "Production API Key",
    key: "pk_live_5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u",
    created: "2023-01-15",
    lastUsed: "2023-06-18",
    status: "active",
    permissions: ["read", "write", "delete"],
  },
  {
    id: "key_2b3c4d5e",
    name: "Development API Key",
    key: "pk_test_6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v",
    created: "2023-02-20",
    lastUsed: "2023-06-17",
    status: "active",
    permissions: ["read", "write"],
  },
  {
    id: "key_3c4d5e6f",
    name: "Analytics API Key",
    key: "pk_analytics_7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w",
    created: "2023-03-10",
    lastUsed: "2023-06-15",
    status: "active",
    permissions: ["read"],
  },
  {
    id: "key_4d5e6f7g",
    name: "Legacy API Key",
    key: "pk_legacy_8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x",
    created: "2022-11-05",
    lastUsed: "2023-05-20",
    status: "inactive",
    permissions: ["read", "write", "delete"],
  },
  {
    id: "key_5e6f7g8h",
    name: "Webhook API Key",
    key: "pk_webhook_9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y",
    created: "2023-04-25",
    lastUsed: "2023-06-18",
    status: "active",
    permissions: ["read", "write"],
  },
]

// API Usage Data
export const apiUsageData: APIUsageData[] = [
  { date: "2023-06-12", requests: 12500, errors: 125, latency: 245 },
  { date: "2023-06-13", requests: 13200, errors: 132, latency: 238 },
  { date: "2023-06-14", requests: 14100, errors: 98, latency: 242 },
  { date: "2023-06-15", requests: 15800, errors: 158, latency: 255 },
  { date: "2023-06-16", requests: 16500, errors: 82, latency: 230 },
  { date: "2023-06-17", requests: 15200, errors: 76, latency: 225 },
  { date: "2023-06-18", requests: 17800, errors: 89, latency: 235 },
]

// Activity Data
export const activityData: ActivityData[] = [
  { date: "2023-06-12", logins: 1250, transactions: 850, apiCalls: 12500 },
  { date: "2023-06-13", logins: 1320, transactions: 920, apiCalls: 13200 },
  { date: "2023-06-14", logins: 1410, transactions: 980, apiCalls: 14100 },
  { date: "2023-06-15", logins: 1580, transactions: 1050, apiCalls: 15800 },
  { date: "2023-06-16", logins: 1650, transactions: 1120, apiCalls: 16500 },
  { date: "2023-06-17", logins: 1520, transactions: 1080, apiCalls: 15200 },
  { date: "2023-06-18", logins: 1780, transactions: 1250, apiCalls: 17800 },
]

// Overview Data
export const overviewData: OverviewData[] = [
  { name: "Jan", total: 1500 },
  { name: "Feb", total: 1700 },
  { name: "Mar", total: 2000 },
  { name: "Apr", total: 2400 },
  { name: "May", total: 2800 },
  { name: "Jun", total: 3200 },
  { name: "Jul", total: 3500 },
  { name: "Aug", total: 3700 },
  { name: "Sep", total: 3300 },
  { name: "Oct", total: 3000 },
  { name: "Nov", total: 2800 },
  { name: "Dec", total: 3200 },
]

// Profile Data
export const profileData: ProfileData = {
  name: "John Doe",
  email: "john.doe@example.com",
  role: "Administrator",
  bio: "Experienced financial professional with over 10 years in the industry.",
  phone: "+1 (555) 123-4567",
  location: "New York, USA",
  joinDate: "January 15, 2022",
}

// Security Settings
export const securitySettings: SecuritySetting[] = [
  {
    id: "2fa",
    name: "Two-Factor Authentication",
    description: "Add an extra layer of security to your account",
    enabled: true,
  },
  {
    id: "login-alerts",
    name: "Login Alerts",
    description: "Receive notifications for new login attempts",
    enabled: true,
  },
  {
    id: "device-management",
    name: "Device Management",
    description: "Manage devices that have access to your account",
    enabled: false,
  },
  {
    id: "session-timeout",
    name: "Session Timeout",
    description: "Automatically log out after period of inactivity",
    enabled: true,
  },
  {
    id: "ip-restriction",
    name: "IP Restrictions",
    description: "Restrict access to specific IP addresses",
    enabled: false,
  },
]

// Notification Settings
export const notificationSettings: NotificationSetting[] = [
  {
    id: "email-alerts",
    name: "Email Alerts",
    description: "Receive important notifications via email",
    enabled: true,
  },
  {
    id: "push-notifications",
    name: "Push Notifications",
    description: "Receive notifications on your mobile device",
    enabled: true,
  },
  {
    id: "transaction-alerts",
    name: "Transaction Alerts",
    description: "Get notified about new transactions",
    enabled: true,
  },
  {
    id: "security-alerts",
    name: "Security Alerts",
    description: "Receive alerts about security-related events",
    enabled: true,
  },
  {
    id: "marketing-emails",
    name: "Marketing Emails",
    description: "Receive promotional emails and offers",
    enabled: false,
  },
  {
    id: "product-updates",
    name: "Product Updates",
    description: "Get notified about new features and updates",
    enabled: true,
  },
]
